sudo: required

dist: trusty

stages:
  - lint
  - test

language: python

jobs:
  include:
    - stage: lint
      install:
        - pip install -r requirements.txt
        - pip install flake8
      script:
        - flake8 numphy

    - stage: test
      services:
        - docker
      env:
        - IMG=adreeve/python-numpy:latest
      install:
        - docker pull $IMG
      script:
        - docker run -t --rm -v `pwd`:/root/numphy -w /root/numphy $IMG bash -c "pip install -r requirements.txt && python -m unittest tests"
