sudo: required

dist: trusty

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      script:
        - echo "done"

    - stage: test
      services:
        - docker
      env:
        - IMG=adreeve/python-numpy:latest
      script:
        - docker pull $IMG
        - docker run -t --rm -v `pwd`:/root/numphy -w /root/numphy $IMG "pip install -r requirements.txt && python -m unittest tests"
